version: '3.8'
services:
  db:
    image: postgres:16
    container_name: puneroomie-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: puneroomie
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
