[phases.setup]
nixPkgs = ["jdk17", "maven"]

[phases.build]
cmds = [
  "cd backend",
  "chmod +x ./mvnw", 
  "./mvnw -Dmaven.multiModuleProjectDirectory=/app/backend -DoutputFile=target/mvn-dependency-list.log -B -DskipTests clean dependency:list install"
]

[start]
cmd = "cd backend && java -Dspring.profiles.active=railway -jar target/room-link-backend-0.0.1-SNAPSHOT.jar"