server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/puneroomie}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  jwt.secret: ${JWT_SECRET:c3VwZXJkdXBlcnNlY3JldHN1cGVyc2VjcmV0c3VwZXJzZWNyZXQ=}
  jwt.expirationMs: ${JWT_EXPIRATION_MS:604800000}
  cors.allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}

logging:
  level:
    root: INFO
    org.springframework.security: WARN
