server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:puneroomie
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  jwt.secret: c3VwZXJkdXBlcnNlY3JldHN1cGVyc2VjcmV0c3VwZXJzZWNyZXQ=
  jwt.expirationMs: 604800000
  cors.allowed-origins: http://localhost:5173

logging:
  level:
    org.springframework.security: INFO
